### ISSUE TITLE
net-config or net-config2?

### ISSUE THREAD

**Issue by andig** [andig/moode#1]
@moodeaudio why do we need two?

**Comment by moodeaudio** [comment]
I forgot about that. I made it b4 you starting working on moode.

see I was planning ahead lol.

i'll delete it after I drink some coffee

**Comment by moodeaudio** [comment]
disregard previous — was not quite awake yet and though u were referring to the repo name ‘moodeaudio’ vs ‘moode’

net-config2.php can b deleted. i might have copied it off b4 making a bunch of changes to the original.

Tim

**Comment by andig** [comment]
Gone it is ;)
