### ISSUE TITLE
player_wrk log

### ISSUE THREAD

**Issue by andig** [andig/moode#10]
I've finally broken my install: changed (digiamp+) mixer to hardware and now:
-  now audio (also after reboot)
- mpd-config hangs when called twice
- after first call player_wrk starts hogging all cpu
- mpd refuses connection

any idea where to check? log file?

Can I trigger a frist-time install from the command line? player_wrk seems to support a first time install?

**Comment by moodeaudio** [comment]
Ouch!

Is this with virgin 2.1 ?

**Comment by andig** [comment]
Hehe, mine is far from virgin. I'll try resetting repo to first commit and check if it works. To see the delta a log file would be good as otherwise its a black box, but there is none, right?

**Comment by andig** [comment]
And do you know if digiamp plus should work with hw mixer?

**Comment by moodeaudio** [comment]
IQaudIO DigiAMP+ works perfect w hardware volume and logarithmic curve. I have one connected to HSU STF-2 sub and KEF Q60 mains.

**Comment by moodeaudio** [comment]
Ive had PHP hang when I accidentally fat-fingerer php.ini and half a commented setting became uncommented. It took me two days to work that one out...

**Comment by andig** [comment]
Mhm. Seems something (definitely not me) has changed permissions for `/run` to something else than 777 which breaks session writing and may have got the worker stuck.

**Comment by andig** [comment]
I'll add some logging. Still gets stuck but I can see that its in the worker, just not sure why yet...

**Comment by andig** [comment]
Finally found it. Using session_save_path after starting a session is apparently no good idea on php 5.6...

**Comment by andig** [comment]
Turned out to be a PHP change with version 5.4 and following: http://stackoverflow.com/questions/32139840/why-cant-daemon-attach-to-php-session/32164649#32164649

**Comment by moodeaudio** [comment]
Nice work tracking that one down :-) Is there a patch?

**Comment by andig** [comment]
See this https://github.com/andig/moode/commit/4f4f949f5903c0dbcb42f0559ea2af79d1e7392b for part of a bigger update- all session read and write access is wrapped in a non-root-user section that allows access to the actual session file (though not much else...)
