### ISSUE TITLE
is orionprofile used for anything?

### ISSUE THREAD

**Issue by andig** [andig/moode#12]

**Comment by andig** [comment]
and djmount?

**Comment by moodeaudio** [comment]
Yes, its a cfg_engine column that contains the value of "Kernel latency”  input field on System config screen. The value is used during Player startup as input arg to orion_optimize.sh which tweeks some system settings that in theory (a) “optimize” kernel latency for audio and (b) make subtle changes in SQ. There are a couple users that prefer the SQ when using ACX or the Orion settings over the Default stock Raspbian settings. I personally cannot tell diff in SQ. I think best to leave the feature for now but I would like to determine whether the “killall’s” at the beginning of orion_optimize.sh are really necessary.

**Comment by moodeaudio** [comment]
Yes,. djmount is col in cfg_engine table that contains value from System config screen YES/NO radio button “DLNA server”. When YES djmount = 1. The value is checked during player startup in player_wrk.php and determines whether to start the DLNA server (minidlna) which indexes /var/lib/mpd/music and then mount (djmount) it’s index to /mnt/UPNP. This allows a UPnP client like VLC for example running on a Laptop to browse the music files and then play back locally.
