### ISSUE TITLE
Session handling

### ISSUE THREAD

**Issue by andig** [andig/moode#14]
From what I understand we're reusing the same session for the whole system. Why then are we- on each request- reading the database into the session that is persisted anyway? Would it suffice to do this on first-time installation only?
Or rather: why is certain data stored in the session and others in the db?

**Comment by moodeaudio** [comment]
Are you referring to these calls "playerSession(‘open’”… that appear in multiple scripts?

**Comment by andig** [comment]
> Are you referring to these calls "playerSession(‘open’”… that appear in multiple scripts?

Yep. I don't get why we're attaching to the saved session with all its variables only to read everything from db again?

**Comment by moodeaudio** [comment]
The comment below in playerSession() function suggests that player_wrk.php maintains separate session id? Very confusing...
"// read PHP SESSION ID stored in SQLite datastore and use it to "attatch" the same SESSION (used in worker)"

**Comment by andig** [comment]
> suggests that player_wrk.php maintains separate session

No, not separate. The session is used to hand the frontend tasks over to the daemon. Same session. I've implemented the loading now, if it turns out we don't need it then we can still throw it out.

**Comment by andig** [comment]
Got it half-working. Crunching through tests...
