### ISSUE TITLE
root fs full

### ISSUE THREAD

**Issue by andig** [andig/moode#18]
My root filesystem has run full:

```
Filesystem            1K-blocks       Used Available Use% Mounted on
/dev/root               1536680    1387580     67696  96% /
```

`raspi-config` is not able to expand it as the the "layout is not supported". Any idea why (we're using Raspbian?) and how?

**Comment by moodeaudio** [comment]
I think “layout not supported” error might be because rootfs is on partition 3 instead of 2. Part 2 was used for ramdisk originally. Try moode script to resize SD Card. It is setup for partition 3.  Here is command: /var/www/tcmods/r22/cmds/resizefs.sh start

**Comment by andig** [comment]
Excellent, working.
