### ISSUE TITLE
is hashCFG() still good for anything?

### ISSUE THREAD

**Issue by andig** [andig/moode#3]

**Comment by moodeaudio** [comment]
All the hashing stuff can be cut out. The two Italians thought it would be useful to protect config files managed by the UI from user hacking.

My experience in troubleshooting 100’s of user issues is that hacked files have accounted for 0% of root causes.

Tim

**Comment by andig** [comment]
And gone.... https://github.com/andig/moode/commit/cec3baf6f19c0a3a309f49599205033d911b5944
