### ISSUE TITLE
is there any logic that overwrites the config files, e.g. nginx.conf?

### ISSUE THREAD

**Issue by andig** [andig/moode#5]
Seems my hand-crafted nginx config is gone??

**Comment by moodeaudio** [comment]
Not any more. I deleted all the config file copy-over code a few releases back. There used to be a dir named /var/www/_OS_SETTINGS that had all the files. U won’t see that on Moode 2.1

I might have missed something. I’ll check today,

Tim

**Comment by andig** [comment]
Found it- problem on my side ;)

**Comment by andig** [comment]
Reopening. My PHP cli ini just got changed again. Same for the comands/watchdog.

Any idea why and where? This is... sneaky?

**Comment by moodeaudio** [comment]
None that I am aware of. 

In release 2.1 I commented out all the conf file maintenance code in player_lib.php, function wrk_sysEnv(), and deleted /var/www/_OS_SETTINGS dir.The only change to conf and ini files on 2.2 distro (host rp3) is the catch-all rule in nginx.conf, otherwise they are same as from 2.1 release.

**Comment by andig** [comment]
I'm suspecting something in the boot process, setting's gone after restart as far as I see.

> Am 27.08.2015 um 19:40 schrieb Tim Curtis notifications@github.com:
> 
> None that I am aware of. 
> 
> In release 2.1 I commented out all the conf file maintenance code in player_lib.php, function wrk_sysEnv(), and deleted /var/www/_OS_SETTINGS dir.The only change to conf and ini files on 2.2 distro (host rp3) is the catch-all rule in nginx.conf, otherwise they are same as from 2.1 release.
>

**Comment by moodeaudio** [comment]
Still not seeing this behavior on my 2.2 image. I changed a timeout setting in nginx.conf, rebooted, started the player and the change was still there.

**Comment by andig** [comment]
Could you e.h. Change th session.save_path in /etc/php/cli/php.ini which is used by the daemon? Test reboot?

> Am 27.08.2015 um 23:43 schrieb Tim Curtis notifications@github.com:
> 
> Still not seeing this behavior on my 2.2 image. I changed a timeout setting in nginx.conf, rebooted, started the player and the change was still there. 
>

**Comment by moodeaudio** [comment]
Changed session.save_path from “/run” to “~”, reboot, start player and its “~”. Change back to “/run” reboot, start player and its “/run”. Repeated this on 3 other PI’s and same. 

I’m not seeing the behavior u describe on my 2.2 image.

**Comment by andig** [comment]
Stupid me, it was broken in git and I've never fixed it https://github.com/andig/moode-etc/blob/master/php5/cli/php.ini
