### ISSUE TITLE
why are playall and enqueueall doing the same?

### ISSUE THREAD

**Issue by andig** [andig/moode#7]
See https://github.com/andig/moode/blob/master/inc/player_lib.php#L77

**Comment by moodeaudio** [comment]
I think enqueueAll() was part of the Library code which was written by a dev named Joel Takvorian (jotak).

The original code for the two functions is below.

function playAll($sock, $json) {
    if (count($json) > 0) {
        // Clear, add first file and play
            $commands = array();
        array_push($commands, "clear");
        array_push($commands, "add \"".html_entity_decode($json[0]['file'])."\"");
        array_push($commands, "play");
            chainMpdCommands($sock, $commands);

```
    // Then add remaining
    $commands = array();
    for ($i = 1; $i < count($json); $i++) {
                array_push($commands, "add \"".html_entity_decode($json[$i]['file'])."\"");
        }
        chainMpdCommands($sock, $commands);
}
```

}

function enqueueAll($sock, $json) {
    $commands = array();
        foreach ($json as $song) {
                $path = $song["file"];
        array_push($commands, "add \"".html_entity_decode($path)."\"");
        }
    chainMpdCommands($sock, $commands);
}

**Comment by andig** [comment]
also ui-wise it's being called by different functions. I'm wondering if playall should have a play command with it in the end in case playback is currently suspended?

**Comment by moodeaudio** [comment]
look in /db/index.php for where the ‘play’ cmds are being sent for the Library. I don’t remember why its this way.

**Comment by andig** [comment]
Solution like this should work?

```
function _queueFiles($json, $commands = array()) {
    foreach ($json as $song) {
        array_push($commands, 'add "' . html_entity_decode($song["file"]) . '"');
    }
    return $commands;
}

function enqueueAll($sock, $json) {
    $commands = _queueFiles($json);
    return chainMpdCommands($sock, $commands);
}

function playAll($sock, $json) {
    $commands = _queueFiles($json);
    array_push($commands, "play");
    return chainMpdCommands($sock, $commands);
}

function playAllReplace($sock, $json) {
    $commands = _queueFiles($json, array("clear"));
    array_push($commands, "play");
    return chainMpdCommands($sock, $commands);
}
```

**Comment by moodeaudio** [comment]
go for it :-)

the entire MPD command interface needs an overhaul. i always thought it had too many moving parts.
