### ISSUE TITLE
What is purpose of tcmods?

### ISSUE THREAD

**Issue by andig** [andig/moode#9]
e.h. why is especially `readtcmconf`being called all over?

**Comment by moodeaudio** [comment]
My lazy file based hack to avoid using the sqlite db for these settings. At the time it was easier/faster to just nano a conf file than edit a sql table, copy back and forth, etc. I gradually made more use of sql table, but not before tcmods.conf became a monster!

Architecturally what is needed is a single “settings” table that provides PHP and JS exact same settings at any given moment. 

The "read, change-setting ,update" sequence is to ensure using most recent settiing.

Obviously using a conf file and reading and updating the entire file just to change one setting is not optimum lol

Tim

**Comment by andig** [comment]
Mhm. A simple settings table consisting of category, key, value? Sounds simple. I'm afraid though youll need to take a stab, that whole playersession thing is killing me.

Also the read things to assign to (other) global vars to output to template.... Sucks ;)

> Am 17.08.2015 um 18:55 schrieb Tim Curtis notifications@github.com:
> 
> My lazy file based hack to avoid using the sqlite db for these settings. At the time it was easier/faster to just nano a conf file than edit a sql table, copy back and forth, etc. I gradually made more use of sql table, but not before tcmods.conf became a monster!
> 
> Architecturally what is needed is a single “settings” table that provides PHP and JS exact same settings at any given moment. 
> 
> The "read, change-setting ,update" sequence is to ensure using most recent settiing.
> 
> Obviously using a conf file and reading and updating the entire file just to change one setting is not optimum lol
> 
> Tim
>

**Comment by moodeaudio** [comment]
No prob. At some point I’ll migrate tcmods.conf settings to cfg_engine sql table and then convert the code to make sql calls instead of file read/update calls.

**Comment by andig** [comment]
> that whole playersession thing is killing me

playersession is moved to ConfigDB class in the current repo. Clearer structure, less madness in the code. Still entirely buggy though.
